django-webpack/django-webpack-loader

- README.md
Hi,
The `webpack.config.js` example in `README.md` can't work, I think correct it would be better.
Thanks.
> Correct the webpack.config.js example in README

- webpack_loader/templatetags/webpack_loader.py
Django 1.9's simple_tag wraps tag output in conditional_escape,
therefore we have to explicitly mark the return value of render_bundle
as safe.
https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape
> mark_safe() the output of template tags

- webpack_loader/utils.py
Per https://docs.python.org/3/library/exceptions.html:
> programmers are encouraged to derive new exceptions from the Exception
> class or one of its subclasses, and not from BaseException.
Specifically deriving from BaseException prevents Jinja2 from handling
errors and Django from displaying the debug page when the webpack build
fails, because Jinja2 catches Exception (this is the logical behavior):
https://github.com/mitsuhiko/jinja2/blob/5b498453b5898257b2287f14ef6c363799f1405a/jinja2/environment.py#L1009
> Derive exceptions from Exception.

- .travis.yml
- setup.py
- tests/app/tests/test_webpack.py
- tests/install.sh
- tests/requirements.txt
- tests/tox.ini
- webpack_loader/templatetags/webpack_loader.py
- webpack_loader/utils.py
Since django 1.6 comes with python 2.6 support, so this commit includes
a patch for python 2.6 compatibility.
Besides, djang-jinja > v2.0 drops support for django < 1.8, so in the
tests, we need to use two django-jinja versions, for both django < 1.8
and django >= 1.8, respectively.
> Fix compatibility with django 1.6

- setup.py
There is no need to install the LICENSE file. It would end up in a global
namespace, possibly overwriting an identically named file there.
> Do not install LICENsE as a datafile.

- README.md
Make the example consistent with detailed explanation. The current example and documentation lead to several assumptions and are generally confusing due to inconsistency.
> fix inconsistent documentation

- tests/app/tests/test_webpack.py
- webpack_loader/exceptions.py
- webpack_loader/loader.py
This commit adds an error message when the bundle name could not be resolved.
Addresses issue #67
> Added an exception when bundle name is not valid

- requirements-dev.txt
- tests/app/tests/test_webpack.py
- tests/webpack.config.gzipTest.js
- webpack_loader/templatetags/webpack_loader.py
As discussed in #74 I made a simple addition to the render_bundle template tag to handle .js.gz and .css.gz files.
I also added some missing requirements to requirements_dev.txt for any future contributors.
> Added support for .js.gz and .css.gz files

- webpack_loader/loader.py
Addressing https://github.com/owais/django-webpack-loader/issues/69.
I'm also using TypeScript (the `ts-loader` with webpack) and it doesn't output the key `error` in `webpack-stats.json`.
I'll send PRs to the ts-loader (we basically just need to add the `error` key [here](https://github.com/TypeStrong/ts-loader/blob/04b84dfc8ed0ae79da8f6248fd3beab45cb3d070/index.ts#L109-L114)) as well to get this sorted out properly.
I also noticed that https://github.com/owais/webpack-bundle-tracker does not [output the filename at all](https://github.com/owais/webpack-bundle-tracker/blob/e6498ecd896c5169db849949a31c5478e8c5e3d5/index.js#L45-L49). I'm thinking about submitting a PR for that too :)
> Fixing bug when error is missing

- webpack_loader/templatetags/webpack_loader.py
django-countries does it the same way, see
https://github.com/SmileyChris/django-countries/commit/0477bdb56
> Avoid the assignment_tag deprecation warning

- README.md
- webpack_loader/templatetags/webpack_loader.py
- webpack_loader/utils.py
As briefly discussed in #95.
From the commit message:
> Rather than doing the work in the template tags, we do the work in utils
functions so that the same functionality is available directly to Python
application code.
>
> This can be useful for `media` properties on Django widgets (#95).
>
> The README has been updated to provide simple examples of usage.
It feels a bit weird to mostly cut & paste code between the files but it seems that that is most of what is needed. I'm not sure that the `get_as_tags` function is exactly necessary but it seemed like it might save someone some trouble if they wanted to achieve similar results.
Very happy to change any and all of it. Especially the names of functions. Naming is hard :) 
I've attempted to provide a bit of README and doc strings but they …
> Create util functions from templatetags code

- setup.py
This allows people to pip install from github directly, since the rst version of the README file is generated upon submission to pypi, but not when git cloning.
(As I mentioned in #95)
> Check if autogenerated README exists, else use version tracked README

- README.md
These lines weren't rendering as the headers they're notated to be. Looks worse on the PyPi page [django-webpack-loader](https://pypi.python.org/pypi/django-webpack-loader/0.4.1). My fix causes it to render correctly on GitHub hopefully that will transfer over. Thanks for the work!
**Before** | **After**
--- | ---
[Page before fix](https://github.com/ezhome/django-webpack-loader#install) | [Page after fix](https://github.com/3ygun/django-webpack-loader/blob/fa80fe51666498bbd460aedc5ae9d1d02717c542/README.md#install)
> Fixed README headers rendering issue

- examples/hot-reload/server.js
When I change something on the page I got following error from update request:
```XMLHttpRequest cannot load http://localhost:3000/assets/bundles/108f5136d63f38ea9442.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.```
Fix was to add Access control header to hot reload server responses.
> Fix for No 'Access-Control-Allow-Origin' header is present error.

- README.md
Needs to be a raw string otherwise it contains invalid escapes.
> Fix example IGNORE patterns

- README.md
Updates the docs to clarify a gotcha with `BUNDLE_DIR_NAME`, as reported by #100.
I don't know what changed between django `1.8` to `2.2` but it took me a good while to figure out that the `/` was the issue now on django `2.2`.
> Updates README.md to clarify a gotcha

- README.md
- tests/app/tests/test_custom_loaders.py
- webpack_loader/__init__.py
- webpack_loader/config.py
- webpack_loader/loader.py
- webpack_loader/utils.py
This project has been a huge value add for us, and I'd like to help address some of the issues around adding custom loader class support. It sounds like the approach outlined in #83 gives the most flexibility for extending the loader.  #202 looks like it's pretty close to that implementation, but given that it's been almost three months since opening (without any edits), and the change is relatively small, I'd like to open a new PR in hopes of getting these changes upstream.
Changes:
`LOADER_CLASS` on the `WEBPACK_CONFIG` setting is now where the loader class is defined. To retain backward compatibility and to keep getting started simple, this defaults to the existing `WebpackLoader` class.
`WebpackLoader._load_assets` has been renamed to `WebpackLoader.load_assets`. This keeps the API …
> Add custom LOADER_CLASS support

- .circleci/config.yml
- tests/app/settings.py
- tests/app/urls.py
- tests/requirements/django22.txt
Hi there! I'm crossing my fingers that this works, to support an upgrade that I'm currently doing. These seemed more expedient (and useful) than running the tests locally. That said, I've never used CircleCI, so it's possible it will break due to an error on my part.
The Django 2.2 jobs also use a more recent version of django-jinja for better compatibility ([changelog](https://github.com/niwinz/django-jinja/blob/master/CHANGES.adoc))
> Add Django 2.2 and Python 3.8 to CI config

- README.md
Adds a link in the README to [Django Manifest Loader](https://github.com/shonin/django-manifest-loader), an actively maintained project that solves the same problem.
> add alternative package to readme

- README.md
add https://github.com/AccordBox/python-webpack-boilerplate to `Alternatives` section in readme
> add Python Webpack Boilerplate

- README.md
There is a small typo in README.md, tests/README.md.
Should read `milliseconds` rather than `miliseconds`.
> docs: Fix simple typo, miliseconds -> milliseconds

- .gitignore
- README.md
- examples/code-splitting/app/settings.py
- examples/code-splitting/package.json
- examples/hot-reload/app/settings.py
- examples/hot-reload/package.json
- examples/simple/app/settings.py
- examples/simple/package.json
> Update examples to use webpack-bundle-tracker@1.0.0

- webpack_loader/__init__.py
RemovedInDjango41Warning: 'webpack_loader' defines default_app_config = 'webpack_loader.apps.WebpackLoaderConfig'. Django now detects this configuration automatically. You can remove default_app_config.
> Fix RemovedInDjango41Warning

- .gitignore
- CHANGELOG.md
- tests/app/settings.py
- tests/app/tests/test_custom_loaders.py
- tests/app/tests/test_webpack.py
- tests/webpack.config.error.js
- tests/webpack.config.gzipTest.js
- tests/webpack.config.simple.js
- tests/webpack.config.sourcemaps.js
- tests/webpack.config.split.js
- webpack_loader/loader.py
> Applies ignore rule before checking assets

- .circleci/config.yml
- requirements-dev.txt
- setup.py
- tests/app/templates/home-deduplicated.jinja
- tests/app/tests/test_webpack.py
- tests/requirements/common.txt
- tests/tox.ini
- tests/webpack.config.skipCommon.js
- webpack_loader/contrib/jinja2ext.py
- webpack_loader/templatetags/webpack_loader.py
As discussed in #296, I've added tests to work with Jinja and cleaned up the test suite to remove python3.5 and update to `Jinja2>3` since python3.5 has reached EOL. `Django<2.2` is also non-LTS.
> Add skip_common_chunks functionality

- README.md
- tests/app/templates/home-duplicated.jinja
- tests/app/tests/test_webpack.py
- webpack_loader/templatetags/webpack_loader.py
This fixes for cases when the programmer uses less common methods for template generation.
> Fixes #300, failsafe request checking

- README.md
- webpack_loader/templatetags/webpack_loader.py
> Fix get_files on readme

- setup.py
Hi Maintainers!
When running a license checker like [Trivy](https://github.com/aquasecurity/trivy), it becomes obvious that this package doesn't have a license defined for the package metadata.
This PR fixes that. In theory, the setup should move from `setup.py` to a `pyproject.toml` but I didn't want to open this box of pandora right now. 😅 
Best  
Ronny
> Set missing "license" package metadata attribute

- .circleci/config.yml
- setup.py
This PR adds formal support for Python 3.12 since there are no changes required.
> Add Python 3.12 to test matrix and add classifier

- .github/dependabot.yml
- examples/README.md
- examples/code-splitting/package-lock.json
- examples/code-splitting/package.json
- examples/code-splitting/webpack.config.js
- examples/hot-reload/README.md
- examples/hot-reload/package-lock.json
- examples/hot-reload/package.json
- examples/hot-reload/server.js
- examples/hot-reload/webpack.config.js
- examples/simple/package-lock.json
- examples/simple/package.json
- examples/simple/webpack.config.js
Examples were using older versions of dependencies, including v1 of webpack-bundle-tracker, which lead to compatibility issues like #344 
This PR updates all npm dependencies on the examples folders to their latest versions, migrates the webpack config to the latest schema, and setups dependabot to automatically create PRs weekly with npm or pip updates
Resolves #344
> Update examples dependencies & setup dependabot

- .circleci/config.yml
- Makefile
- README.md
- requirements-dev.txt
- tests/package-lock.json
- tests/webpack.config.error.js
- tests/webpack.config.gzipTest.js
- tests/webpack.config.integrity.js
- tests/webpack.config.simple.js
- tests/webpack.config.skipCommon.js
- tests/webpack.config.sourcemaps.js
- tests/webpack.config.split.js
Add a `make test` command to make it easier to run tests locally.
Also ensures the virtual env is activated before running tests or build.
Adds basic development documentation about the makefile.
> Add make test & development documentation

- .github/dependabot.yml
Address https://github.com/django-webpack/django-webpack-loader/pull/402#issuecomment-2168530156
- Disable `dependabot` updates for old webpack 4 tests
---
Related docs
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
> Disable `dependabot` updates for old webpack 4 tests
